
'use client';

import * as React from 'react';
import { useActionState } from 'react';
import { useFormStatus } from 'react-dom';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import Image from 'next/image';

import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent } from '@/components/ui/card';
import { generateImageAction } from '@/app/actions';
import { useToast } from '@/hooks/use-toast';
import { Skeleton } from '@/components/ui/skeleton';

const formSchema = z.object({
  promptText: z.string().min(3, {
    message: 'Prompt must be at least 3 characters.',
  }),
});

type FormSchemaType = z.infer<typeof formSchema>;

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending} className="w-full bg-accent hover:bg-accent/90 text-accent-foreground" size="sm">
      {pending ? 'Generating Image...' : 'Generate Image'}
    </Button>
  );
}

export function ImageCreator() {
  const { toast } = useToast();
  
  const [state, formAction] = useActionState(generateImageAction, {
    message: '',
    data: undefined,
    error: undefined,
  });

  const form = useForm<FormSchemaType>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      promptText: '',
    },
  });

  React.useEffect(() => {
    if (state.message && !state.error) {
      toast({
        title: "Success!",
        description: state.message,
        variant: "default",
      });
      // form.reset(); // Optionally reset form
    } else if (state.error) {
      toast({
        title: 'Image Generation Error',
        description: state.error,
        variant: 'destructive',
      });
    }
  }, [state, toast]);

  const { pending } = useFormStatus();


  return (
    <Card className="shadow-none border-none">
      <CardContent className="p-2">
        <Form {...form}>
          <form action={formAction} className="space-y-4">
            <FormField
              control={form.control}
              name="promptText"
              render={({ field }) => (
                <FormItem>
                  <FormLabel htmlFor="promptText" className="text-sm font-medium">Image Prompt</FormLabel>
                  <FormControl>
                    <Textarea
                      id="promptText"
                      placeholder="e.g., A futuristic cityscape at sunset"
                      className="text-sm min-h-[80px]"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <SubmitButton />
          </form>
        </Form>

        {pending && (
          <div className="mt-4 space-y-2">
            <p className="text-sm text-muted-foreground text-center">Generating your image, please wait...</p>
            <Skeleton className="h-[200px] w-full rounded-md" />
          </div>
        )}

        {!pending && state.data?.imageDataUri && (
          <div className="mt-4">
            <h4 className="text-sm font-medium mb-2">Generated Image:</h4>
            <div className="relative aspect-square w-full overflow-hidden rounded-md border">
              <Image
                src={state.data.imageDataUri}
                alt="Generated by AI"
                fill
                className="object-contain"
                data-ai-hint="generated image"
              />
            </div>
             <p className="text-xs text-muted-foreground mt-1">
                Note: Images are experimental and may take a few moments to generate.
             </p>
          </div>
        )}
        {!pending && !state.data?.imageDataUri && state.message && !state.error && (
           <p className="text-sm text-muted-foreground mt-4 text-center">
            Image generated, but no data URI was returned.
          </p>
        )}
         {!pending && !state.data?.imageDataUri && !state.error && !state.message && (
          <p className="text-sm text-muted-foreground mt-4 text-center">
            Enter a prompt to generate an image.
          </p>
        )}
      </CardContent>
    </Card>
  );
}
